use NUMERIC instead of INT
vmaas=> select rpmver_array('3.6.0.v20120721114722');
ERROR:  integer out of range
CONTEXT:  PL/pgSQL function rpmver_array(character varying) line 52 at assignment